services:
  anidream-api:
    image: anidream.api
    container_name: anidream-api
    restart: always
    ports:
      - "5001:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
        restart: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./AnidreamStorage:/app/AnidreamStorage
        
  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: UAZ9233
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
