// <auto-generated />
using System;
using Anidream.Api.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anidream.Api.DataAccess.Migrations
{
    [DbContext(typeof(AnidreamContext))]
    [Migration("20250809082126_Add entities (Director, Studio); Update entity (Media)")]
    partial class AddentitiesDirectorStudioUpdateentityMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anidream.Api.Domain.Entities.Director", b =>
                {
                    b.Property<Guid>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DirectorId");

                    b.ToTable("Directors", (string)null);
                });

            modelBuilder.Entity("Anidream.Api.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("CurrentEpisodes")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uuid");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("integer");

                    b.HasKey("MediaId");

                    b.HasIndex("DirectorId");

                    b.HasIndex("StudioId");

                    b.ToTable("Medias", (string)null);
                });

            modelBuilder.Entity("Anidream.Api.Domain.Entities.Studio", b =>
                {
                    b.Property<Guid>("StudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("StudioId");

                    b.ToTable("Studios", (string)null);
                });

            modelBuilder.Entity("Anidream.Api.Domain.Entities.Media", b =>
                {
                    b.HasOne("Anidream.Api.Domain.Entities.Director", "Director")
                        .WithMany("Medias")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anidream.Api.Domain.Entities.Studio", "Studio")
                        .WithMany("Medias")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("Anidream.Api.Domain.Entities.Director", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Anidream.Api.Domain.Entities.Studio", b =>
                {
                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
